// Code generated by "stringer -type=MinipoolStatus"; DO NOT EDIT.

package contracts

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Prelaunch-0]
	_ = x[Launched-1]
	_ = x[Staking-2]
	_ = x[Withdrawable-3]
	_ = x[Finished-4]
	_ = x[Canceled-5]
	_ = x[Error-6]
}

const _MinipoolStatus_name = "PrelaunchLaunchedStakingWithdrawableFinishedCanceledError"

var _MinipoolStatus_index = [...]uint8{0, 9, 17, 24, 36, 44, 52, 57}

func (i MinipoolStatus) String() string {
	if i >= MinipoolStatus(len(_MinipoolStatus_index)-1) {
		return "MinipoolStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MinipoolStatus_name[_MinipoolStatus_index[i]:_MinipoolStatus_index[i+1]]
}
